name: Jaeger operator
version: 0.0.6
services:
  NodeGroupInventoryWallet:
    annotations: {}
    apiVersion: core.meshery.io/v1alpha1
    dependsOn:
    - jaeger-operator
    id: null
    isAnnotation: null
    labels: {}
    model: meshery-core
    name: NodeGroupInventoryWallet
    namespace: ""
    settings: {}
    traits:
      meshmap:
        edges: []
        fieldRefData: {}
        id: a6216ed2-941c-4b35-94c3-dbcc2093e4fa
        label: NodeGroupInventoryWallet
        meshmodel-data:
          category:
            metadata: null
            name: Orchestration & Management
          components: null
          description: ""
          displayName: Meshery Core
          hostID: 26e64aa8-2d86-57bd-92b3-2a73160d27b4
          id: 3e2db384-d3af-5fac-8af2-684fc3c29446
          metadata:
            isAnnotation: false
            subCategory: App Definition and Development
            svgColor: ui/public/static/img/meshmodels/meshery-core/color/meshery-core-color.svg
            svgComplete: ""
            svgWhite: ui/public/static/img/meshmodels/meshery-core/color/meshery-core-color.svg
          model:
            version: 0.7.1
          name: meshery-core
          registrant:
            hostname: artifacthub
          relationships: null
          schemaVersion: core.meshery.io/v1beta1
          status: enabled
          subCategory: App Definition and Development
          version: v1.0.0
        meshmodel-metadata:
          capabilities: |-
            {
              "designer": {
                "pass-events-to": "parent",
                "edit": {
                  "config": false,
                  "copy": false,
                  "delete": false,
                  "duplicate": false,
                  "reset-styles": false,
                  "resolve": false,
                  "lock": false,
                  "shape": {
                    "convert-shape": false
                  },
                  "style": false
                },
                "label": {
                  "edit": false,
                  "show": false,
                  "sync-with-config-property": "none"
                }
              }
            }
          defaultData: '{"label":""}'
          definition:
            component:
              kind: NodeGroupInventoryWallet
              schema: '{}'
              version: core.meshery.io/v1alpha1
            description: ""
            displayName: NodeGroupInventoryWallet
            duplicates: 1
            format: JSON
            id: 2feda916-2084-4a19-ad31-e26b70b3b8ec
            metadata:
              capabilities: |-
                {
                  "designer": {
                    "pass-events-to": "parent",
                    "edit": {
                      "config": false,
                      "copy": false,
                      "delete": false,
                      "duplicate": false,
                      "reset-styles": false,
                      "resolve": false,
                      "lock": false,
                      "shape": {
                        "convert-shape": false
                      },
                      "style": false
                    },
                    "label": {
                      "edit": false,
                      "show": false,
                      "sync-with-config-property": "none"
                    }
                  }
                }
              defaultData: '{"label":""}'
              genealogy: parent
              hasInvalidSchema: true
              isAnnotation: true
              primaryColor: '#00B39F'
              secondaryColor: '#00D3A9'
              shape: round-rectangle
              shapePolygonPoints: ""
              status: enabled
              styleOverrides: '{"height":"30px","width":"30px", "background-image":"none","border-width":0,"border-style":"dashed","background-opacity":0.1,"data":{"label":""}}'
              styles: '{"height":"30px","width":"30px", "background-image":"none","border-width":0,"border-style":"dashed","background-opacity":0.1}'
              subCategory: ""
              svgColor: ui/public/static/img/meshmodels/meshery-core/color/anchornode-color.svg
              svgComplete: ""
              svgWhite: ui/public/static/img/meshmodels/meshery-core/white/anchornode-white.svg
            model:
              category:
                metadata: null
                name: Orchestration & Management
              components: null
              description: ""
              displayName: Meshery Core
              hostID: 26e64aa8-2d86-57bd-92b3-2a73160d27b4
              id: 3e2db384-d3af-5fac-8af2-684fc3c29446
              metadata:
                isAnnotation: false
                subCategory: App Definition and Development
                svgColor: ui/public/static/img/meshmodels/meshery-core/color/meshery-core-color.svg
                svgComplete: ""
                svgWhite: ui/public/static/img/meshmodels/meshery-core/color/meshery-core-color.svg
              model:
                version: 0.7.1
              name: meshery-core
              registrant:
                hostname: artifacthub
              relationships: null
              schemaVersion: core.meshery.io/v1beta1
              status: enabled
              subCategory: App Definition and Development
              version: v1.0.0
            schemaVersion: core.meshery.io/v1beta1
            version: v1.0.0
          genealogy: parent
          hasInvalidSchema: true
          isAnnotation: true
          primaryColor: '#00B39F'
          secondaryColor: '#00D3A9'
          shape: round-rectangle
          shapePolygonPoints: ""
          status: enabled
          styleOverrides:
            background-image: none
            background-opacity: 0.1
            border-style: dashed
            border-width: 0
            data:
              label: ""
            height: 30px
            width: 30px
            z-index: 3
          styles: '{"height":"30px","width":"30px", "background-image":"none","border-width":0,"border-style":"dashed","background-opacity":0.1}'
          subCategory: ""
          svgColor: ui/public/static/img/meshmodels/meshery-core/color/anchornode-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/meshery-core/white/anchornode-white.svg
        parent: 04ce0461-2ce3-481f-a807-60f2c6437747
        position:
          posX: 130
          posY: 150
        whiteboardData: {}
    type: NodeGroupInventoryWallet
    version: 0.7.1
  jaeger-operator:
    annotations: {}
    apiVersion: apps/v1
    dependsOn: []
    id: null
    isAnnotation: null
    labels: {}
    model: kubernetes
    name: jaeger-operator
    namespace: default
    settings:
      spec:
        template:
          spec:
            containers:
            - args:
              - start
              env:
              - name: LOG-LEVEL
                value: debug
              image: jaegertracing/jaeger-operator:master
              name: jaeger-operator
    traits:
      meshmap:
        edges: []
        fieldRefData: {}
        id: 04ce0461-2ce3-481f-a807-60f2c6437747
        meshmodel-metadata:
          capabilities: |2-
             {
              "designer": {
                "edit": {
                  "shape": {
                    "convert-shape": false
                  }
                }
              }
            }
          defaultData: ""
          genealogy: parent
          isAnnotation: false
          isCustomResource: false
          isModelAnnotation: "FALSE"
          isNamespaced: true
          logoURL: Created by Meshery Authors
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          secondaryColor: '#7aa1f0'
          shape: round-pentagon
          shapePolygonPoints: ""
          status: enabled
          styleOverrides: '{"border-width":2,"background-opacity":0.5}'
          styles: '{"border-width":2,"background-opacity":0.5}'
          subCategory: ""
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/deployment-color.svg
          svgComplete: ui/public/static/img/meshmodels/kubernetes/complete/deployment-complete.svg
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/deployment-white.svg
        position:
          posX: 130
          posY: 150
        whiteboardData:
          style: {}
    type: Deployment
    version: ""
