name: Pod Priviledged Simple
version: 0.0.8
services:
  privileged-simple-pod:
    annotations: {}
    apiVersion: v1
    dependsOn: []
    id: null
    isAnnotation: null
    labels: {}
    model: kubernetes
    name: privileged-simple-pod
    namespace: default
    settings:
      spec:
        containers:
        - command:
          - sleep
          - "3600"
          image: busybox
          name: privileged-simple-pod
          security Context:
            privileged: true
    traits:
      meshmap:
        edges: []
        fieldRefData: {}
        id: 725ad21e-2209-4b8e-8e25-0ec819b212cf
        meshmodel-metadata:
          capabilities: ""
          genealogy: ""
          isAnnotation: false
          isCustomResource: false
          isModelAnnotation: "FALSE"
          isNamespaced: true
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-rectangle
          styleOverrides: ""
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/kubernetes-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/kubernetes-white.svg
        position:
          posX: 290
          posY: 290
        whiteboardData:
          style: {}
    type: Pod
    version: ""
