name: QAT-TLS-handshake-acceleration-for-Istio.yaml
services:
  For Xin:
    name: For Xin
    type: Comment
    apiVersion: core.meshery.io/v1alpha1
    version: v1.0.0
    model: meshery
    settings:
      usersMessages:
      - avatarUrl: https://pbs.twimg.com/profile_images/880205475643441152/V_vhfnzb_400x400.jpg
        firstName: Lee
        lastName: Calcote
        message: Hi Xin, congratulations on your publishing of this design into the
          Meshery Catalog. This is very cool.
        timestamp: "2023-08-22T02:26:56.097Z"
        userid: 090e7114-509a-4046-81f1-9c5fb8daf724
    traits:
      meshmap:
        edges: []
        id: f761abf8-ea11-473c-9cb3-bbd0543f2a66
        label: For Xin
        meshmodel-data:
          category:
            metadata: null
            name: Orchestration & Management
          displayName: Meshery
          displayhostname: ""
          hostID: 00000000-0000-0000-0000-000000000000
          hostname: ""
          metadata:
            svgColor: ui/public/static/img/meshmodels/meshery/color/broker-color.svg
            svgWhite: ui/public/static/img/meshmodels/aws-node-termination-handler-2/white/terminator-white.svg
          name: meshery
          version: v1.0.0
        meshmodel-metadata:
          genealogy: ""
          isAnnotation: true
          isNamespaced: false
          logoURL: ""
          model: meshery
          modelDisplayName: Meshery
          primaryColor: '#FFDE00'
          published: true
          secondaryColor: '#FFDE00'
          shape: tag
          styleOverrides: ""
          subCategory: App Definition and Development
          svgColor: ui/public/static/img/meshmodels/meshery/color/comment-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/meshery/color/comment-color.svg
        position:
          posX: 376.4944895815154
          posY: 328.68183840946824
  example-istiocontrolplane:
    name: example-istiocontrolplane
    type: IstioOperator
    apiVersion: install.istio.io/v1alpha1
    namespace: istio-system
    model: istio-base
    settings:
      spec:
        components:
          egress Gateways:
          - enabled: true
            name: istio-egressgateway
          ingress Gateways:
          - enabled: true
            k8s:
              pod Annotations:
                proxy.istio.io/config: |
                  privateKeyProvider:
                    qat:
                      pollDelay: 10ms
            name: istio-ingressgateway
        profile: demo
    traits:
      meshmap:
        edges: []
        id: 0a9190c6-3b94-4497-9b5e-0e26e26a3f4a
        label: example-istiocontrolplane
        meshmodel-metadata:
          isCustomResource: true
          isNamespaced: true
          primaryColor: '#326CE5'
          secondaryColor: '#7aa1f0'
          shape: circle
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/apiservice-color.svg
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/apiservice-white.svg
        position:
          posX: 434.0383661148126
          posY: 209.19159803556587
  intel-qat-plugin:
    name: intel-qat-plugin
    type: DaemonSet
    apiVersion: apps/v1
    namespace: qat-device-plugin
    model: kubernetes
    settings:
      spec:
        revisionHistoryLimit: 10
        selector:
          matchLabels:
            app: intel-qat-plugin
        template:
          metadata:
            annotations:
              container.apparmor.security.beta.kubernetes.io/intel-qat-plugin: unconfined
            labels:
              app: intel-qat-plugin
          spec:
            automountServiceAccountToken: false
            containers:
            - image: intel/intel-qat-plugin:0.25.0
              imagePullPolicy: IfNotPresent
              name: intel-qat-plugin
              resources: {}
              securityContext:
                allowPrivilegeEscalation: false
                readOnlyRootFilesystem: true
                seLinuxOptions:
                  type: container_device_plugin_t
              volumeMounts:
              - mountPath: /dev/vfio
                name: devdir
                readOnly: true
              - mountPath: /sys/kernel/debug
                name: debugfsdir
                readOnly: true
              - mountPath: /sys/bus/pci
                name: pcidir
              - mountPath: /var/lib/kubelet/device-plugins
                name: kubeletsockets
            dnsPolicy: ClusterFirst
            nodeSelector:
              kubernetes.io/arch: amd64
            restartPolicy: Always
            schedulerName: default-scheduler
            securityContext: {}
            volumes:
            - hostPath:
                path: /dev/vfio
                type: ""
              name: devdir
            - hostPath:
                path: /sys/kernel/debug
                type: ""
              name: debugfsdir
            - hostPath:
                path: /sys/bus/pci
                type: ""
              name: pcidir
            - hostPath:
                path: /var/lib/kubelet/device-plugins
                type: ""
              name: kubeletsockets
        updateStrategy:
          rollingUpdate:
            maxSurge: 0
            maxUnavailable: 1
          type: RollingUpdate
    traits:
      meshmap:
        edges: []
        id: 8e79be8c-da6a-49fe-8bc2-6decf12fd7c2
        label: intel-qat-plugin
        meshmodel-metadata:
          genealogy: parent
          isCustomResource: false
          isNamespaced: true
          logoURL: Created by Lee
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-pentagon
          styleOverrides: '{"background-image":"none","border-width":2,"background-opacity":0.5}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/daemonset-color.svg
          svgComplete: ui/public/static/img/meshmodels/kubernetes/complete/daemonset-complete.svg
          svgWhite: ui/public/static/img/meshmodels/kubernetes/color/daemonset-color.svg
        position:
          posX: 366.5383661148126
          posY: 209.69159803556587
  istio-operator-bkxxj:
    name: istio-operator
    type: ClusterRole
    apiVersion: rbac.authorization.k8s.io/v1
    model: kubernetes
    settings:
      rules:
      - api Groups:
        - authentication.istio.io
        resources:
        - '*'
        verbs:
        - '*'
      - api Groups:
        - config.istio.io
        resources:
        - '*'
        verbs:
        - '*'
      - api Groups:
        - install.istio.io
        resources:
        - '*'
        verbs:
        - '*'
      - api Groups:
        - networking.istio.io
        resources:
        - '*'
        verbs:
        - '*'
      - api Groups:
        - security.istio.io
        resources:
        - '*'
        verbs:
        - '*'
      - api Groups:
        - admissionregistration.k8s.io
        resources:
        - mutatingwebhookconfigurations
        - validatingwebhookconfigurations
        verbs:
        - '*'
      - api Groups:
        - apiextensions.k8s.io
        resources:
        - customresourcedefinitions.apiextensions.k8s.io
        - customresourcedefinitions
        verbs:
        - '*'
      - api Groups:
        - apps
        - extensions
        resources:
        - daemonsets
        - deployments
        - deployments/finalizers
        - replicasets
        verbs:
        - '*'
      - api Groups:
        - autoscaling
        resources:
        - horizontalpodautoscalers
        verbs:
        - '*'
      - api Groups:
        - monitoring.coreos.com
        resources:
        - servicemonitors
        verbs:
        - get
        - create
        - update
      - api Groups:
        - policy
        resources:
        - poddisruptionbudgets
        verbs:
        - '*'
      - api Groups:
        - rbac.authorization.k8s.io
        resources:
        - clusterrolebindings
        - clusterroles
        - roles
        - rolebindings
        verbs:
        - '*'
      - api Groups:
        - coordination.k8s.io
        resources:
        - leases
        verbs:
        - get
        - create
        - update
      - api Groups:
        - ""
        resources:
        - configmaps
        - endpoints
        - events
        - namespaces
        - pods
        - pods/proxy
        - pods/portforward
        - persistentvolumeclaims
        - secrets
        - services
        - serviceaccounts
        - resourcequotas
        verbs:
        - '*'
    traits:
      meshmap:
        edges:
        - data:
            id: b1b7c93a-a79f-43aa-af37-f5673699b1f9
            metadata: c3ad3045-b7a5-4b15-bafc-55ad9cc2bce6
            source: f9e95f4b-ffef-4523-917c-1442bb59b53b
            subType: Permission
            target: 9240267f-d393-4c5d-bdf9-596bacf0ebf0
        - data:
            id: 20dbd465-ec1f-4569-9e6e-d78aedd120fe
            metadata:
              binded_by: c3ad3045-b7a5-4b15-bafc-55ad9cc2bce6
            source: f9e95f4b-ffef-4523-917c-1442bb59b53b
            subType: Permission
            target: 9240267f-d393-4c5d-bdf9-596bacf0ebf0
        id: f9e95f4b-ffef-4523-917c-1442bb59b53b
        label: istio-operator
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: false
          logoURL: Created by Lee
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-rectangle
          styleOverrides: '{"height":"22px","width":"16px","padding":"6px"}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/clusterrole-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/clusterrole-white.svg
        position:
          posX: 396.8322029513953
          posY: 415.8531281641976
  istio-operator-hovyx:
    name: istio-operator
    type: Service
    apiVersion: v1
    namespace: istio-operator
    model: kubernetes
    settings:
      spec:
        ports:
        - name: http-metrics
          port: 80
          protocol: TCP
          target Port: 8383
        selector:
          name: istio-operator
    traits:
      meshmap:
        edges:
        - data:
            id: 4d38fff7-27e5-4ad1-a2df-f09e377ffc0f
            metadata:
              port: 80
              protocol: TCP
            source: d24ca3fc-fb37-40d6-86b7-a2665b24f120
            subType: Network
            target: 8e79be8c-da6a-49fe-8bc2-6decf12fd7c1
        id: d24ca3fc-fb37-40d6-86b7-a2665b24f120
        label: istio-operator
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: true
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-triangle
          styleOverrides: '{"height":16,"width":17,"padding":12,"background-fit":"none","background-position-y":4.5}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/apiservice-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/apiservice-white.svg
        position:
          posX: 256.53216476306534
          posY: 416.20650383081477
  istio-operator-tkxiz:
    name: istio-operator
    type: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    namespace: istio-operator
    model: kubernetes
    settings:
      role Ref:
        api Group: rbac.authorization.k8s.io
        kind: ClusterRole
        name: istio-operator
      subjects:
      - kind: ServiceAccount
        name: istio-operator
        namespace: istio-operator
    traits:
      meshmap:
        edges: []
        id: c3ad3045-b7a5-4b15-bafc-55ad9cc2bce6
        label: istio-operator
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: false
          logoURL: Created by Lee
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-rectangle
          styleOverrides: '{"height":"22px","width":"16px","padding":"6px", "z-index":9999}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/clusterrolebinding-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/clusterrolebinding-white.svg
        position:
          posX: 465.1235208236876
          posY: 431.8445718927949
  istio-operator-txmsy:
    name: istio-operator
    type: ServiceAccount
    apiVersion: v1
    namespace: istio-operator
    model: kubernetes
    traits:
      meshmap:
        edges:
        - data:
            id: b1b7c93a-a79f-43aa-af37-f5673699b1f9
            metadata: c3ad3045-b7a5-4b15-bafc-55ad9cc2bce6
            source: f9e95f4b-ffef-4523-917c-1442bb59b53b
            subType: Permission
            target: 9240267f-d393-4c5d-bdf9-596bacf0ebf0
        - data:
            id: 20dbd465-ec1f-4569-9e6e-d78aedd120fe
            metadata:
              binded_by: c3ad3045-b7a5-4b15-bafc-55ad9cc2bce6
            source: f9e95f4b-ffef-4523-917c-1442bb59b53b
            subType: Permission
            target: 9240267f-d393-4c5d-bdf9-596bacf0ebf0
        id: 9240267f-d393-4c5d-bdf9-596bacf0ebf0
        label: istio-operator
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: true
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-rectangle
          styleOverrides: ""
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/serviceaccount-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/color/serviceaccount-color.svg
        position:
          posX: 536.6987263776565
          posY: 422.96867689707653
  istio-operator-utnjj:
    name: istio-operator
    type: Deployment
    apiVersion: apps/v1
    namespace: istio-operator
    model: kubernetes
    settings:
      spec:
        replicas: -1
        revision History Limit: 10
        selector:
          match Labels:
            name: istio-operator
        template:
          metadata:
            annotations:
              prometheus.io/port: "15014"
              prometheus.io/scrape: "true"
            labels:
              name: istio-operator
          spec:
            containers:
            - command:
              - operator
              - server
              - --monitoring-host=127.0.0.1
              - --monitoring-port=15014
              env:
              - name: WATCH_NAMESPACE
                value: istio-system
              - name: LEADER_ELECTION_NAMESPACE
                value: istio-operator
              - name: POD_NAME
                value From:
                  field Ref:
                    field Path: metadata.name
              - name: OPERATOR_NAME
                value: istio-operator
              - name: WAIT_FOR_RESOURCES_TIMEOUT
                value: 300s
              - name: REVISION
                value: ""
              image: docker.io/istio/operator:1.18.0
              name: istio-operator
              resources:
                limits:
                  cpu: 200m
                  memory: 256Mi
                requests:
                  cpu: 50m
                  memory: 128Mi
              security Context:
                allow Privilege Escalation: false
                capabilities:
                  drop:
                  - ALL
                privileged: false
                read Only Root Filesystem: true
                run As Group: 1337
                run As Non Root: true
                run As User: 1337
            service Account Name: istio-operator
    traits:
      meshmap:
        edges:
        - data:
            id: 4d38fff7-27e5-4ad1-a2df-f09e377ffc0f
            metadata:
              port: 80
              protocol: TCP
            source: d24ca3fc-fb37-40d6-86b7-a2665b24f120
            subType: Network
            target: 8e79be8c-da6a-49fe-8bc2-6decf12fd7c1
        id: 8e79be8c-da6a-49fe-8bc2-6decf12fd7c1
        label: istio-operator
        meshmodel-metadata:
          genealogy: parent
          isCustomResource: false
          isNamespaced: true
          logoURL: Created by Lee
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-pentagon
          styleOverrides: '{"background-image":"none","border-width":2,"background-opacity":0.5}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/deployment-color.svg
          svgComplete: ui/public/static/img/meshmodels/kubernetes/complete/deployment-complete.svg
          svgWhite: ui/public/static/img/meshmodels/kubernetes/color/deployment-color.svg
        position:
          posX: 257.4715548501929
          posY: 308.2542360923034
