name: Prometheus-monitoring-ns
services:
  comment-og:
    name: comment-og
    type: Comment
    apiVersion: core.meshery.io/v1alpha1
    version: v1.0.0
    model: meshery
    settings:
      usersMessages:
      - avatarUrl: https://pbs.twimg.com/profile_images/880205475643441152/V_vhfnzb_400x400.jpg
        firstName: Lee
        lastName: Calcote
        message: Looks good
        timestamp: "2023-08-31T14:56:47.699Z"
        userid: 090e7114-509a-4046-81f1-9c5fb8daf724
    traits:
      meshmap:
        edges: []
        id: c24f1817-3581-4296-9420-50428b124d8f
        label: comment-og
        meshmodel-data:
          category:
            metadata: null
            name: Orchestration & Management
          displayName: Meshery
          displayhostname: ""
          hostID: 00000000-0000-0000-0000-000000000000
          hostname: ""
          metadata:
            svgColor: ui/public/static/img/meshmodels/meshery/color/broker-color.svg
            svgWhite: ui/public/static/img/meshmodels/aws-node-termination-handler-2/white/terminator-white.svg
          name: meshery
          version: v1.0.0
        meshmodel-metadata:
          genealogy: ""
          isAnnotation: true
          isNamespaced: false
          logoURL: ""
          model: meshery
          modelDisplayName: Meshery
          primaryColor: '#FFDE00'
          published: true
          secondaryColor: '#FFDE00'
          shape: tag
          styleOverrides: ""
          subCategory: App Definition and Development
          svgColor: ui/public/static/img/meshmodels/meshery/color/comment-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/meshery/color/comment-color.svg
        position:
          posX: 838.2114576884244
          posY: 412.544647781345
  prometheus-config:
    name: prometheus-config
    type: ConfigMap
    apiVersion: v1
    namespace: monitoring
    model: kubernetes
    settings:
      data:
        prometheus.yml: |
          global:
            scrape_interval:     15s
            evaluation_interval: 15s
          alerting:
            alertmanagers:
            - static_configs:
              - targets:
          rule_files:
            # - "example-file.yml"
          scrape_configs:
            - job_name: 'prometheus'
              static_configs:
              - targets: ['147.75.47.9:9100','147.28.149.165:9100']
            - job_name: 'k8services'
              kubernetes_sd_configs:
                  - role: endpoints
              relabel_configs:
                  - source_labels:
                      - __meta_kubernetes_namespace
                      - __meta_kubernetes_service_name
                    action: drop
                    regex: default;kubernetes
                  - source_labels:
                      - __meta_kubernetes_namespace
                    regex: default
                    action: keep
                  - source_labels: [__meta_kubernetes_service_name]
                    target_label: job
    traits:
      meshmap:
        edges: []
        id: 046059d0-992d-40c6-bc3d-a0a4f3f923a2
        label: prometheus-config
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: true
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: circle
          styleOverrides: ""
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/apiservice-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/apiservice-white.svg
        position:
          posX: 937.6854331757138
          posY: 438.7642171982099
  prometheus-deployment:
    name: prometheus-deployment
    type: Deployment
    apiVersion: apps/v1
    namespace: monitoring
    model: kubernetes
    settings:
      spec:
        replicas: 1
        selector:
          match Labels:
            app: prometheus-server
        strategy:
          rolling Update:
            max Surge: 1
            max Unavailable: 1
          type: RollingUpdate
        template:
          metadata:
            labels:
              app: prometheus-server
          spec:
            containers:
            - args:
              - --config.file=/etc/prometheus/prometheus.yml
              - --storage.tsdb.path=/prometheus/
              image: prom/prometheus:v2.2.1
              name: prometheus
              ports:
              - container Port: 9090
              volume Mounts:
              - mount Path: /etc/prometheus/
                name: prometheus-config-volume
              - mount Path: /prometheus/
                name: prometheus-storage-volume
            volumes:
            - config Map:
                default Mode: 420
                name: prometheus-config
              name: prometheus-config-volume
            - name: prometheus-storage-volume
    traits:
      meshmap:
        edges:
        - data:
            id: ef9dd64f-19cd-4863-8d09-cd97646795b9
            metadata:
              port: 8080
              protocol: TCP
            source: 9abf0f27-0f16-4725-845a-ed12bf21f04d
            subType: Network
            target: 1860a126-f6d6-4608-835a-92d4d493872f
        id: 1860a126-f6d6-4608-835a-92d4d493872f
        label: prometheus-deployment
        meshmodel-metadata:
          genealogy: parent
          isCustomResource: false
          isNamespaced: true
          logoURL: Created by leecalcote
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-pentagon
          styleOverrides: '{"background-image":"none","border-width":2,"background-opacity":0.5}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/deployment-color.svg
          svgComplete: ui/public/static/img/meshmodels/kubernetes/complete/deployment-complete.svg
          svgWhite: ui/public/static/img/meshmodels/kubernetes/color/deployment-color.svg
        position:
          posX: 781.1678521670258
          posY: 471.5941821834384
  prometheus-domyv:
    name: prometheus
    type: ClusterRole
    apiVersion: rbac.authorization.k8s.io/v1
    namespace: default
    model: kubernetes
    settings:
      rules:
      - api Groups:
        - ""
        resources:
        - nodes
        - nodes/proxy
        - services
        - endpoints
        - pods
        verbs:
        - get
        - list
        - watch
      - api Groups:
        - extensions
        resources:
        - ingresses
        verbs:
        - get
        - list
        - watch
      - non Resource URLs:
        - /metrics
        verbs:
        - get
    traits:
      meshmap:
        edges: []
        id: 05476151-6319-4da7-b2bd-03707d13fc24
        label: prometheus
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: false
          logoURL: Created by leecalcote
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-rectangle
          styleOverrides: '{"height":"22px","width":"16px","padding":"6px"}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/clusterrole-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/clusterrole-white.svg
        position:
          posX: 1002.6854331757138
          posY: 438.7642171982099
  prometheus-service:
    name: prometheus-service
    type: Service
    apiVersion: v1
    namespace: monitoring
    model: kubernetes
    annotations:
      prometheus.io/path: /
      prometheus.io/port: "8080"
      prometheus.io/scrape: "true"
    settings:
      spec:
        ports:
        - port: 8080
          protocol: TCP
          target Port: 9090
        selector:
          app: prometheus-server
        type: LoadBalancer
    traits:
      meshmap:
        edges:
        - data:
            id: ef9dd64f-19cd-4863-8d09-cd97646795b9
            metadata:
              port: 8080
              protocol: TCP
            source: 9abf0f27-0f16-4725-845a-ed12bf21f04d
            subType: Network
            target: 1860a126-f6d6-4608-835a-92d4d493872f
        id: 9abf0f27-0f16-4725-845a-ed12bf21f04d
        label: prometheus-service
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: true
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-triangle
          styleOverrides: '{"height":16,"width":17,"padding":12,"background-fit":"none","background-position-y":4.5}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/apiservice-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/apiservice-white.svg
        position:
          posX: 670.7633811703876
          posY: 471.5941821834384
  prometheus-vndrd:
    name: prometheus
    type: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    namespace: default
    model: kubernetes
    settings:
      role Ref:
        api Group: rbac.authorization.k8s.io
        kind: ClusterRole
        name: prometheus
      subjects:
      - kind: ServiceAccount
        name: default
        namespace: monitoring
    traits:
      meshmap:
        edges: []
        id: d687260a-7bdf-4298-922d-1a80fbd29b8e
        label: prometheus
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: false
          logoURL: Created by leecalcote
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-rectangle
          styleOverrides: '{"height":"22px","width":"16px","padding":"6px", "z-index":9999}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/clusterrolebinding-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/clusterrolebinding-white.svg
        position:
          posX: 935.6854331757138
          posY: 501.7642171982099
