name: Elastic search
services:
  default:
    name: default
    type: Namespace
    apiVersion: v1
    version: v1.25.2
    model: kubernetes
    traits:
      meshmap:
        edges: []
        id: a5a3d40c-c5b7-4648-850c-f452f59bd8d3
        label: default
        meshmodel-data:
          category:
            metadata: null
            name: Orchestration & Management
          displayName: Kubernetes
          displayhostname: ""
          hostID: 00000000-0000-0000-0000-000000000000
          hostname: ""
          metadata:
            svgColor: ui/public/static/img/meshmodels/kubernetes/color/kubernetes-color.svg
            svgWhite: ui/public/static/img/meshmodels/kubernetes/white/kubernetes-white.svg
          name: kubernetes
          version: v1.25.2
        meshmodel-metadata:
          genealogy: parent
          isCustomResource: false
          isNamespaced: false
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: rectangle
          styleOverrides: '{"background-image":"none","border-width":2,"border-style":"dashed","background-opacity":0.5}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/namespace-color.svg
          svgComplete: ui/public/static/img/meshmodels/kubernetes/complete/namespace-complete.svg
          svgWhite: ui/public/static/img/meshmodels/kubernetes/color/namespace-color.svg
        position:
          posX: 293.47100988242687
          posY: 98.20260314826496
        whiteboardData:
          style:
            z-index: 12
  e079c4ef-e7a9-4ada-895c-5acde4bdb6ad:
    name: e079c4ef-e7a9-4ada-895c-5acde4bdb6ad
    type: Section
    apiVersion: core.meshery.io/v1alpha1
    version: v1.0.0
    model: meshery
    traits:
      meshmap:
        edges: []
        id: e079c4ef-e7a9-4ada-895c-5acde4bdb6ad
        label: ""
        meshmodel-data:
          category:
            metadata: null
            name: Orchestration & Management
          displayName: Meshery
          displayhostname: ""
          hostID: 00000000-0000-0000-0000-000000000000
          hostname: ""
          metadata:
            svgColor: ui/public/static/img/meshmodels/meshery/color/broker-color.svg
            svgWhite: ui/public/static/img/meshmodels/aws-node-termination-handler-2/white/terminator-white.svg
          name: meshery
          version: v1.0.0
        meshmodel-metadata:
          genealogy: parent
          isAnnotation: true
          isNamespaced: false
          logoURL: ""
          model: meshery
          modelDisplayName: Meshery
          primaryColor: '#00B39F'
          published: true
          secondaryColor: '#00D3A9'
          shape: rectangle
          styleOverrides: '{"height":"30px","width":"30px", "background-image":"none","border-width":1,"border-style":"dashed","background-opacity":0.1,"data":{"label":""}}'
          subCategory: App Definition and Development
          svgColor: ui/public/static/img/meshmodels/meshery/color/broker-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/aws-node-termination-handler-2/white/terminator-white.svg
        position:
          posX: 461.0665593447481
          posY: 187.61606182488947
        whiteboardData:
          style:
            z-index: 14
  elasticsearch:
    name: elasticsearch
    type: ServiceAccount
    apiVersion: v1
    namespace: default
    version: v1.25.2
    model: kubernetes
    annotations:
      name: elasticsearch
    settings:
      image Pull Secrets: []
      secrets: []
    traits:
      meshmap:
        edges: []
        id: 053f1d4b-ebdc-4e5d-9351-711bf1aa3075
        label: elasticsearch
        meshmodel-data:
          category:
            metadata: null
            name: Orchestration & Management
          displayName: Kubernetes
          displayhostname: ""
          hostID: 00000000-0000-0000-0000-000000000000
          hostname: ""
          metadata:
            svgColor: ui/public/static/img/meshmodels/kubernetes/color/kubernetes-color.svg
            svgWhite: ui/public/static/img/meshmodels/kubernetes/white/kubernetes-white.svg
          name: kubernetes
          version: v1.25.2
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: true
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: bottom-round-rectangle
          styleOverrides: ""
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/serviceaccount-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/color/serviceaccount-color.svg
        position:
          posX: 494.71307347795374
          posY: 92.85237087625924
        whiteboardData:
          style:
            z-index: 11
  elasticsearch-rc:
    name: elasticsearch-rc
    type: ReplicationController
    apiVersion: v1
    namespace: default
    version: v1.25.2
    model: kubernetes
    labels:
      component: elasticsearch
    dependsOn:
    - default
    settings:
      spec:
        replicas: 1
        template:
          metadata:
            labels:
              component: elasticsearch
          spec:
            containers:
            - env:
              - name: KUBERNETES_CA_CERTIFICATE_FILE
                value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
              - name: NAMESPACE
                value From:
                  field Ref:
                    field Path: metadata.namespace
              - name: CLUSTER_NAME
                value: myesdb
              - name: DISCOVERY_SERVICE
                value: elasticsearch
              - name: NODE_MASTER
                value: "true"
              - name: NODE_DATA
                value: "true"
              - name: ""
              - name: HTTP_ENABLE
                value: "true"
              image: quay.io/pires/docker-elasticsearch-kubernetes:5.6.2
              name: es
              ports:
              - container Port: 9200
                name: http
                protocol: TCP
              - container Port: 9300
                name: transport
                protocol: TCP
              security Context:
                capabilities:
                  add:
                  - IPC_LOCK
              volume Mounts:
              - mount Path: /data
                name: storage
            init Containers:
            - command:
              - '["sysctl", "-w", "vm.max_map_count=262144"]'
              image: busybox
              image Pull Policy: IfNotPresent
              name: init-sysctl
              security Context:
                privileged: true
            service Account: elasticsearch
            volumes:
            - name: storage
    traits:
      meshmap:
        edges: []
        id: dc3f0f2f-88be-4dbf-a9f7-c93719e6d4f5
        label: elasticsearch-rc
        meshmodel-data:
          category:
            metadata: null
            name: Orchestration & Management
          displayName: Kubernetes
          displayhostname: ""
          hostID: 00000000-0000-0000-0000-000000000000
          hostname: ""
          metadata:
            svgColor: ui/public/static/img/meshmodels/kubernetes/color/kubernetes-color.svg
            svgWhite: ui/public/static/img/meshmodels/kubernetes/white/kubernetes-white.svg
          name: kubernetes
          version: v1.25.2
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: true
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: cut-rectangle
          styleOverrides: ""
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/kubernetes-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/kubernetes-white.svg
        parent: a5a3d40c-c5b7-4648-850c-f452f59bd8d3
        position:
          posX: 234.9007617034
          posY: 51.27008090330568
        whiteboardData:
          style:
            z-index: 6
  elasticsearch-svc:
    name: elasticsearch-svc
    type: Service
    apiVersion: v1
    namespace: default
    version: v1.25.2
    model: kubernetes
    labels:
      component: elasticsearch
    dependsOn:
    - default
    settings:
      spec:
        ports:
        - name: http
          port: 9200
          protocol: TCP
        - name: transport
          port: 9300
          protocol: TCP
        selector:
          component: elasticsearch
        type: LoadBalancer
    traits:
      meshmap:
        edges: []
        id: 48bf8d87-19e8-4bef-bc19-8ceee94ecdaf
        label: elasticsearch-svc
        meshmodel-data:
          category:
            metadata: null
            name: Orchestration & Management
          displayName: Kubernetes
          displayhostname: ""
          hostID: 00000000-0000-0000-0000-000000000000
          hostname: ""
          metadata:
            svgColor: ui/public/static/img/meshmodels/kubernetes/color/kubernetes-color.svg
            svgWhite: ui/public/static/img/meshmodels/kubernetes/white/kubernetes-white.svg
          name: kubernetes
          version: v1.25.2
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: true
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-triangle
          styleOverrides: '{"height":20,"width":20,"padding":12,"background-fit":"none","background-position-y":4.5,"x":"10px","y":"12px"}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/kubernetes-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/kubernetes-white.svg
        parent: a5a3d40c-c5b7-4648-850c-f452f59bd8d3
        position:
          posX: 236.5041618354061
          posY: 122.76627941706916
        whiteboardData:
          style:
            z-index: 7
  role-binding-es:
    name: role-binding-es
    type: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    namespace: default
    version: v1.25.2
    model: kubernetes
    annotations:
      name: elasticsearch
    dependsOn:
    - default
    settings:
      role Ref:
        api Group: rbac.authorization.k8s.io
        kind: Role
        name: elasticsearch
      subjects:
      - kind: ServiceAccount
        name: elasticsearch
        namespace: default
    traits:
      meshmap:
        edges: []
        id: 46cb9cbb-6fd6-4cb7-9b7d-d9dc1f6cf7fe
        label: role-binding-es
        meshmodel-data:
          category:
            metadata: null
            name: Orchestration & Management
          displayName: Kubernetes
          displayhostname: ""
          hostID: 00000000-0000-0000-0000-000000000000
          hostname: ""
          metadata:
            svgColor: ui/public/static/img/meshmodels/kubernetes/color/kubernetes-color.svg
            svgWhite: ui/public/static/img/meshmodels/kubernetes/white/kubernetes-white.svg
          name: kubernetes
          version: v1.25.2
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: true
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-rectangle
          styleOverrides: '{"height":"25px","width":"25px","x":"7", "y":"7","z-index":4}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/clusterrolebinding-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/clusterrolebinding-white.svg
        parent: a5a3d40c-c5b7-4648-850c-f452f59bd8d3
        position:
          posX: 350.5412580614538
          posY: 51.05980479319266
        whiteboardData:
          style:
            z-index: 9
  role-es:
    name: role-es
    type: Role
    apiVersion: rbac.authorization.k8s.io/v1
    namespace: default
    version: v1.25.2
    model: kubernetes
    annotations:
      name: elasticsearch
    dependsOn:
    - default
    settings:
      rules:
      - api Groups:
        - '""'
        resources:
        - endpoints
        verbs:
        - get
    traits:
      meshmap:
        edges: []
        id: 774de9ac-4f86-4030-a253-2481a7f3b272
        label: role-es
        meshmodel-data:
          category:
            metadata: null
            name: Orchestration & Management
          displayName: Kubernetes
          displayhostname: ""
          hostID: 00000000-0000-0000-0000-000000000000
          hostname: ""
          metadata:
            svgColor: ui/public/static/img/meshmodels/kubernetes/color/kubernetes-color.svg
            svgWhite: ui/public/static/img/meshmodels/kubernetes/white/kubernetes-white.svg
          name: kubernetes
          version: v1.25.2
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: true
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-rectangle
          styleOverrides: '{"height":"22px", "width":"22px", "x":"8.5", "y":"7.5","z-index":4}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/clusterrole-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/clusterrole-white.svg
        parent: a5a3d40c-c5b7-4648-850c-f452f59bd8d3
        position:
          posX: 349.31187352970994
          posY: 128.84540150333726
        whiteboardData:
          style:
            z-index: 8
