name: Pod Liveness
services:
  pods-liveness-exec-pod:
    name: pods-liveness-exec-pod
    type: Pod
    apiVersion: v1
    namespace: default
    model: kubernetes
    settings:
      spec:
        containers:
        - args:
          - /bin/sh
          - -c
          - touch /tmp/healthy; sleep 30; rm -rf /tmp/healthy; sleep 600
          image: busybox
          liveness Probe:
            exec:
              command:
              - cat
              - /tmp/healthy
            initial Delay Seconds: 5
            period Seconds: 5
          name: pods-liveness-exec-container
    traits:
      meshmap:
        edges: []
        id: 79f666dc-796a-4857-8d1f-e5293aab6656
        meshmodel-metadata:
          capabilities: ""
          genealogy: ""
          isAnnotation: false
          isCustomResource: false
          isModelAnnotation: "FALSE"
          isNamespaced: true
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-rectangle
          styleOverrides: ""
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/kubernetes-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/kubernetes-white.svg
        position:
          posX: 110
          posY: 110
        whiteboardData:
          style:
            z-index: 3
