name: Kubernetes Metrics Server Configuration
services:
  metrics-server-auth-reader:
    name: metrics-server-auth-reader
    type: RoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    namespace: kube-system
    model: kubernetes
    labels:
      k8s-app: metrics-server
    settings:
      role Ref:
        api Group: rbac.authorization.k8s.io
        kind: Role
        name: extension-apiserver-authentication-reader
      subjects:
      - kind: ServiceAccount
        name: metrics-server
        namespace: kube-system
    traits:
      meshmap:
        edges: []
        id: 6a1349dd-3de5-4c90-8772-74294267289d
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: true
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-rectangle
          styleOverrides: '{"height":"25px","width":"25px","x":"7", "y":"7","z-index":4}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/clusterrolebinding-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/clusterrolebinding-white.svg
        position:
          posX: -1
          posY: 5
        whiteboardData:
          style:
            z-index: 9
  metrics-server-qmrlm:
    name: metrics-server
    type: Service
    apiVersion: v1
    namespace: kube-system
    model: kubernetes
    labels:
      k8s-app: metrics-server
    settings:
      spec:
        ports:
        - name: https
          port: 443
          protocol: TCP
          target Port: https
        selector:
          k8s-app: metrics-server
    traits:
      meshmap:
        edges: []
        id: 6b181db1-8368-439d-a3b5-e4e4aa787b5d
        label: metrics-server
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: true
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-triangle
          styleOverrides: '{"height":20,"width":20,"padding":12,"background-fit":"none","background-position-y":4.5,"x":"10px","y":"12px"}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/kubernetes-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/kubernetes-white.svg
        position:
          posX: -46.5
          posY: -47.5
        whiteboardData:
          style:
            z-index: 11
  metrics-server-xaysl:
    name: metrics-server
    type: Deployment
    apiVersion: apps/v1
    namespace: kube-system
    model: kubernetes
    labels:
      k8s-app: metrics-server
    settings:
      spec:
        selector:
          match Labels:
            k8s-app: metrics-server
        strategy:
          rolling Update:
            max Unavailable: 0
        template:
          metadata:
            labels:
              k8s-app: metrics-server
          spec:
            containers:
            - args:
              - --cert-dir=/tmp
              - --secure-port=4443
              - --kubelet-preferred-address-types=InternalIP,ExternalIP,Hostname
              - --kubelet-use-node-status-port
              - --metric-resolution=15s
              image: registry.k8s.io/metrics-server/metrics-server:v0.6.4
              image Pull Policy: IfNotPresent
              liveness Probe:
                failure Threshold: 3
                http Get:
                  path: /livez
                  port: https
                  scheme: HTTPS
                period Seconds: 10
              name: metrics-server
              ports:
              - container Port: 4443
                name: https
                protocol: TCP
              readiness Probe:
                failure Threshold: 3
                http Get:
                  path: /readyz
                  port: https
                  scheme: HTTPS
                initial Delay Seconds: 20
                period Seconds: 10
              resources:
                requests:
                  cpu: 100m
                  memory: 200Mi
              security Context:
                allow Privilege Escalation: false
                read Only Root Filesystem: true
                run As Non Root: true
                run As User: 1000
              volume Mounts:
              - mount Path: /tmp
                name: tmp-dir
            node Selector:
              kubernetes.io/os: linux
            priority Class Name: system-cluster-critical
            service Account Name: metrics-server
            volumes:
            - empty Dir: {}
              name: tmp-dir
    traits:
      meshmap:
        edges: []
        id: 64548bc7-775c-40d7-a623-65897b2eda89
        label: metrics-server
        meshmodel-metadata:
          genealogy: parent
          isCustomResource: false
          isNamespaced: true
          logoURL: Created by leecalcote
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-pentagon
          styleOverrides: '{"background-image":"none","border-width":2,"background-opacity":0.5}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/deployment-color.svg
          svgComplete: ui/public/static/img/meshmodels/kubernetes/complete/deployment-complete.svg
          svgWhite: ui/public/static/img/meshmodels/kubernetes/color/deployment-color.svg
        position:
          posX: 40.5
          posY: 52.5
        whiteboardData: {}
  metrics-server-xuaeh:
    name: metrics-server
    type: ServiceAccount
    apiVersion: v1
    namespace: kube-system
    model: kubernetes
    labels:
      k8s-app: metrics-server
    traits:
      meshmap:
        edges:
        - data:
            id: dd82aedf-87c7-4491-80d8-18bc39585a36
            metadata:
              binded_by: f923357d-b595-40fa-ab7b-a2802854c658
            source: 49d332ae-3900-4c13-9cd8-de0112d31aff
            subType: Permission
            target: 4817661a-967a-4e0d-afb9-df155c5645e0
          style:
            curve-style:
              name: curve-style
              strValue: bezier
              value: bezier
            font-family:
              name: font-family
              strValue: Qanelas Soft, sans-serif
              value:
              - Qanelas Soft, sans-serif
              - Qanelas Soft, sans-serif
            font-size:
              name: font-size
              pfValue: 6
              strValue: 6px
              units: px
              value: 6
            line-color:
              mapping:
                mapped:
                  fn: true
                  mapping: true
                name: line-color
                prevFnValue: '#7aa1f0'
                strValue: fn
              name: line-color
              pfValue:
              - 122
              - 161
              - 240
              strValue: rgb(122,161,240)
              value:
              - 122
              - 161
              - 240
            line-style:
              name: line-style
              strValue: dotted
              value: dotted
            target-arrow-shape:
              name: target-arrow-shape
              strValue: vee
              value: vee
            text-events:
              name: text-events
              strValue: "yes"
              value: "yes"
            text-outline-color:
              name: text-outline-color
              pfValue:
              - 255
              - 255
              - 255
              strValue: rgb(255,255,255)
              value:
              - 255
              - 255
              - 255
            text-outline-width:
              name: text-outline-width
              pfValue: 1
              strValue: 1px
              units: px
              value: 1
            text-wrap:
              name: text-wrap
              strValue: wrap
              value: wrap
            width:
              name: width
              pfValue: 1.5
              strValue: 1.5px
              units: px
              value: 1.5
            z-index:
              name: z-index
              pfValue: 999
              strValue: "999"
              value: 999
            z-index-compare:
              name: z-index-compare
              strValue: manual
              value: manual
        id: 4817661a-967a-4e0d-afb9-df155c5645e0
        label: metrics-server
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: true
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: bottom-round-rectangle
          styleOverrides: ""
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/serviceaccount-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/color/serviceaccount-color.svg
        position:
          posX: 52.5
          posY: -53.5
        whiteboardData:
          style:
            z-index: 5
  metrics-server:system:auth-delegator:
    name: metrics-server:system:auth-delegator
    type: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    namespace: default
    model: kubernetes
    labels:
      k8s-app: metrics-server
    settings:
      role Ref:
        api Group: rbac.authorization.k8s.io
        kind: ClusterRole
        name: system:auth-delegator
      subjects:
      - kind: ServiceAccount
        name: metrics-server
        namespace: kube-system
    traits:
      meshmap:
        edges: []
        id: 3724dcfc-a0f3-4ebc-b596-ce2ab5b785b3
        label: metrics-server:system:auth-delegator
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: false
          logoURL: Created by leecalcote
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-rectangle
          styleOverrides: '{"height":"25px","width":"25px","x":"7", "y":"7"}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/clusterrolebinding-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/clusterrolebinding-white.svg
        position:
          posX: -50
          posY: 5
        whiteboardData:
          style:
            z-index: 8
  system:aggregated-metrics-reader:
    name: system:aggregated-metrics-reader
    type: ClusterRole
    apiVersion: rbac.authorization.k8s.io/v1
    namespace: default
    model: kubernetes
    labels:
      k8s-app: metrics-server
      rbac.authorization.k8s.io/aggregate-to-admin: "true"
      rbac.authorization.k8s.io/aggregate-to-edit: "true"
      rbac.authorization.k8s.io/aggregate-to-view: "true"
    settings:
      rules:
      - api Groups:
        - metrics.k8s.io
        resources:
        - pods
        - nodes
        verbs:
        - get
        - list
        - watch
    traits:
      meshmap:
        edges: []
        id: 0a3a6d4a-3c51-47cf-a6f4-8fa7fee668bb
        label: system:aggregated-metrics-reader
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: false
          logoURL: Created by leecalcote
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-rectangle
          styleOverrides: '{"height":"22px", "width":"22px", "x":"8.5", "y":"7.5"}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/clusterrole-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/clusterrole-white.svg
        position:
          posX: -5.5
          posY: 52.5
        whiteboardData:
          style:
            z-index: 12
  system:metrics-server-meiof:
    name: system:metrics-server
    type: ClusterRole
    apiVersion: rbac.authorization.k8s.io/v1
    namespace: default
    model: kubernetes
    labels:
      k8s-app: metrics-server
    settings:
      rules:
      - api Groups:
        - ""
        resources:
        - nodes/metrics
        verbs:
        - get
      - api Groups:
        - ""
        resources:
        - pods
        - nodes
        verbs:
        - get
        - list
        - watch
    traits:
      meshmap:
        edges:
        - data:
            id: dd82aedf-87c7-4491-80d8-18bc39585a36
            metadata:
              binded_by: f923357d-b595-40fa-ab7b-a2802854c658
            source: 49d332ae-3900-4c13-9cd8-de0112d31aff
            subType: Permission
            target: 4817661a-967a-4e0d-afb9-df155c5645e0
          style:
            curve-style:
              name: curve-style
              strValue: bezier
              value: bezier
            font-family:
              name: font-family
              strValue: Qanelas Soft, sans-serif
              value:
              - Qanelas Soft, sans-serif
              - Qanelas Soft, sans-serif
            font-size:
              name: font-size
              pfValue: 6
              strValue: 6px
              units: px
              value: 6
            line-color:
              mapping:
                mapped:
                  fn: true
                  mapping: true
                name: line-color
                prevFnValue: '#7aa1f0'
                strValue: fn
              name: line-color
              pfValue:
              - 122
              - 161
              - 240
              strValue: rgb(122,161,240)
              value:
              - 122
              - 161
              - 240
            line-style:
              name: line-style
              strValue: dotted
              value: dotted
            target-arrow-shape:
              name: target-arrow-shape
              strValue: vee
              value: vee
            text-events:
              name: text-events
              strValue: "yes"
              value: "yes"
            text-outline-color:
              name: text-outline-color
              pfValue:
              - 255
              - 255
              - 255
              strValue: rgb(255,255,255)
              value:
              - 255
              - 255
              - 255
            text-outline-width:
              name: text-outline-width
              pfValue: 1
              strValue: 1px
              units: px
              value: 1
            text-wrap:
              name: text-wrap
              strValue: wrap
              value: wrap
            width:
              name: width
              pfValue: 1.5
              strValue: 1.5px
              units: px
              value: 1.5
            z-index:
              name: z-index
              pfValue: 999
              strValue: "999"
              value: 999
            z-index-compare:
              name: z-index-compare
              strValue: manual
              value: manual
        id: 49d332ae-3900-4c13-9cd8-de0112d31aff
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: false
          logoURL: Created by leecalcote
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-rectangle
          styleOverrides: '{"height":"22px", "width":"22px", "x":"8.5", "y":"7.5"}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/clusterrole-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/clusterrole-white.svg
        position:
          posX: -51.5
          posY: 52.5
        whiteboardData:
          style:
            z-index: 10
  system:metrics-server-olnrb:
    name: system:metrics-server
    type: ClusterRoleBinding
    apiVersion: rbac.authorization.k8s.io/v1
    namespace: default
    model: kubernetes
    labels:
      k8s-app: metrics-server
    settings:
      role Ref:
        api Group: rbac.authorization.k8s.io
        kind: ClusterRole
        name: system:metrics-server
      subjects:
      - kind: ServiceAccount
        name: metrics-server
        namespace: kube-system
    traits:
      meshmap:
        edges: []
        id: f923357d-b595-40fa-ab7b-a2802854c658
        label: system:metrics-server
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: false
          logoURL: Created by leecalcote
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: round-rectangle
          styleOverrides: '{"height":"25px","width":"25px","x":"7", "y":"7"}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/clusterrolebinding-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/clusterrolebinding-white.svg
        position:
          posX: 0.7193665469320933
          posY: -0.7235851343731028
        whiteboardData:
          style:
            z-index: 6
  v1beta1.metrics.k8s.io:
    name: v1beta1.metrics.k8s.io
    type: APIService
    apiVersion: apiregistration.k8s.io/v1
    namespace: default
    model: kubernetes
    labels:
      k8s-app: metrics-server
    settings:
      spec:
        group: metrics.k8s.io
        group Priority Minimum: 100
        insecure Skip TLS Verify: true
        service:
          name: metrics-server
          namespace: kube-system
        version: v1beta1
        version Priority: 100
    traits:
      meshmap:
        edges: []
        id: ac4b6ef8-0103-4e9c-b944-42e9a113dcc2
        label: v1beta1.metrics.k8s.io
        meshmodel-metadata:
          genealogy: ""
          isCustomResource: false
          isNamespaced: false
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          published: true
          secondaryColor: '#7aa1f0'
          shape: triangle
          styleOverrides: '{"height":"23px","width":"23px","x":"7", "y":"14"}'
          subCategory: Scheduling & Orchestration
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/apiservice-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/apiservice-white.svg
        position:
          posX: 47
          posY: 4
        whiteboardData:
          style:
            z-index: 7
