name: mongoDB-Sample-app
services:
  sample-app:
    name: sample-app
    type: ServiceAccount
    apiVersion: v1
    namespace: default
    model: kubernetes
    labels:
      app.kubernetes.io/instance: sample-app
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: sample-app
      app.kubernetes.io/version: 0.1.0
      helm.sh/chart: sample-app-0.1.0
    traits:
      meshmap:
        edges: []
        id: 9a0ca95c-ffcc-4678-a14d-2145126d4e4a
        meshmodel-metadata:
          capabilities: ""
          defaultData: ""
          genealogy: ""
          isAnnotation: false
          isCustomResource: false
          isModelAnnotation: "FALSE"
          isNamespaced: true
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          secondaryColor: '#7aa1f0'
          shape: bottom-round-rectangle
          shapePolygonPoints: ""
          status: enabled
          styleOverrides: ""
          styles: ""
          subCategory: ""
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/serviceaccount-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/serviceaccount-white.svg
        position:
          posX: -69
          posY: 89
        whiteboardData:
          style: {}
  sample-app-backend-fygsq:
    name: sample-app-backend
    type: Service
    apiVersion: v1
    namespace: default
    model: kubernetes
    labels:
      app: sample-app-backend
      app.kubernetes.io/instance: sample-app
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: sample-app
      app.kubernetes.io/version: 0.1.0
      helm.sh/chart: sample-app-0.1.0
    settings:
      spec:
        ports:
        - name: http
          port: 8000
          protocol: TCP
          target Port: http
        selector:
          app: sample-app-backend
          app.kubernetes.io/instance: sample-app
          app.kubernetes.io/name: sample-app
        type: ClusterIP
    traits:
      meshmap:
        edges:
        - data:
            id: c276617a-5c31-42e4-9519-b43bdc79e1fa
            metadata:
              port: 8000
              protocol: TCP
            source: ac414466-82c8-4d4e-aa5b-b6a98c3879b4
            subType: Network
            target: 01823411-984c-47f4-926c-d0793cdb4ebe
          style:
            control-point-distances: null
            control-point-weights: "0.5"
            curve-style: bezier
            haystack-radius: "0"
            line-color: rgb(153,153,153)
            line-style: dotted
            opacity: "1"
            segment-distances: 20px
            segment-weights: "0.5"
            target-arrow-shape: vee
            taxi-direction: auto
            taxi-turn: 50%
            taxi-turn-min-distance: 10px
            width: 1.5px
        id: ac414466-82c8-4d4e-aa5b-b6a98c3879b4
        meshmodel-metadata:
          capabilities: ""
          defaultData: ""
          genealogy: ""
          isAnnotation: false
          isCustomResource: false
          isModelAnnotation: "FALSE"
          isNamespaced: true
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          secondaryColor: '#7aa1f0'
          shape: round-triangle
          shapePolygonPoints: ""
          status: enabled
          styleOverrides:
            background-position-y: 4.5
            height: 20
            padding: 12
            width: 20
            x: 10px
            "y": 12px
            z-index: 3
          styles: '{"height":20,"width":20,"padding":12,"background-position-y":4.5,"x":"10px","y":"12px"}'
          subCategory: ""
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/service-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/service-white.svg
        position:
          posX: -51.5
          posY: 20
        whiteboardData:
          style: {}
  sample-app-backend-lypxp:
    name: sample-app-backend
    type: Deployment
    apiVersion: apps/v1
    namespace: default
    model: kubernetes
    labels:
      app.kubernetes.io/instance: sample-app
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: sample-app
      app.kubernetes.io/version: 0.1.0
      helm.sh/chart: sample-app-0.1.0
    settings:
      spec:
        replicas: 1
        selector:
          match Labels:
            app: sample-app-backend
            app.kubernetes.io/instance: sample-app
            app.kubernetes.io/name: sample-app
        template:
          metadata:
            labels:
              app: sample-app-backend
              app.kubernetes.io/instance: sample-app
              app.kubernetes.io/name: sample-app
          spec:
            containers:
            - command:
              - python3
              - main.py
              env:
              - name: DB_URL
                value From:
                  secret Key Ref:
                    key: connectionString.standard
                    name: <resource-name>-<database>-<user>
              - name: DB_NAME
                value: admin
              image: quay.io/mongodb/farm-intro-backend:0.1
              image Pull Policy: Always
              name: sample-app
              ports:
              - container Port: 8000
                name: http
                protocol: TCP
              resources: {}
              security Context: {}
            security Context: {}
            service Account Name: sample-app
    traits:
      meshmap:
        edges:
        - data:
            id: c276617a-5c31-42e4-9519-b43bdc79e1fa
            metadata:
              port: 8000
              protocol: TCP
            source: ac414466-82c8-4d4e-aa5b-b6a98c3879b4
            subType: Network
            target: 01823411-984c-47f4-926c-d0793cdb4ebe
          style:
            control-point-distances: null
            control-point-weights: "0.5"
            curve-style: bezier
            haystack-radius: "0"
            line-color: rgb(153,153,153)
            line-style: dotted
            opacity: "1"
            segment-distances: 20px
            segment-weights: "0.5"
            target-arrow-shape: vee
            taxi-direction: auto
            taxi-turn: 50%
            taxi-turn-min-distance: 10px
            width: 1.5px
        id: 01823411-984c-47f4-926c-d0793cdb4ebe
        meshmodel-metadata:
          capabilities: |-
            {
              "fieldRefs": [
                {
                  "fieldPath": "spec.template.spec.containers",
                  "jsonSchemaPath": "properties.spec.allOf[0].properties.template.allOf[0].properties.spec.allOf[0].properties.containers.items.allOf[0]",
                  "component": {
                    "kind": "Container",
                    "model": "meshery-core"
                  },
                  "renderChildren": true
                }
              ],
              "designer": {
                "edit": {
                  "shape": {
                    "convert-shape": false
                  }
                }
              }
            }
          defaultData: ""
          genealogy: parent
          isAnnotation: false
          isCustomResource: false
          isModelAnnotation: "FALSE"
          isNamespaced: true
          logoURL: Created by Meshery Authors
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          secondaryColor: '#7aa1f0'
          shape: round-rectangle
          shapePolygonPoints: ""
          status: enabled
          styleOverrides:
            background-opacity: 0.5
            border-width: 2
            z-index: 3
          styles: '{"border-width":2,"background-opacity":0.5}'
          subCategory: ""
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/deployment-color.svg
          svgComplete: ui/public/static/img/meshmodels/kubernetes/complete/deployment-complete.svg
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/deployment-white.svg
        position:
          posX: 44.5
          posY: -62
        whiteboardData:
          style: {}
  sample-app-frontend-eoczc:
    name: sample-app-frontend
    type: Deployment
    apiVersion: apps/v1
    namespace: default
    model: kubernetes
    labels:
      app: sample-app-frontend
      app.kubernetes.io/instance: sample-app
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: sample-app
      app.kubernetes.io/version: 0.1.0
      helm.sh/chart: sample-app-0.1.0
    settings:
      spec:
        replicas: 1
        selector:
          match Labels:
            app: sample-app-frontend
            app.kubernetes.io/instance: sample-app
            app.kubernetes.io/name: sample-app
        template:
          metadata:
            labels:
              app: sample-app-frontend
              app.kubernetes.io/instance: sample-app
              app.kubernetes.io/name: sample-app
          spec:
            containers:
            - env:
              - name: DANGEROUSLY_DISABLE_HOST_CHECK
                value: "true"
              - name: SVC_BACKEND
                value: sample-app-backend:8000
              image: quay.io/mongodb/farm-intro-frontend:0.1
              image Pull Policy: Always
              name: sample-app
              ports:
              - container Port: 3000
                name: http
                protocol: TCP
              resources: {}
              security Context: {}
            security Context: {}
            service Account Name: sample-app
    traits:
      meshmap:
        edges:
        - data:
            id: 0274aef1-7b3d-49a1-91fd-9c8978e74a25
            metadata:
              port: 3000
              protocol: TCP
            source: 141a267b-480a-451e-b7a6-4af5692dbca8
            subType: Network
            target: 348d4e06-f4c8-4a0f-bbe5-94c79fea7ea7
          style:
            control-point-distances: null
            control-point-weights: "0.5"
            curve-style: bezier
            haystack-radius: "0"
            line-color: rgb(153,153,153)
            line-style: dotted
            opacity: "1"
            segment-distances: 20px
            segment-weights: "0.5"
            target-arrow-shape: vee
            taxi-direction: auto
            taxi-turn: 50%
            taxi-turn-min-distance: 10px
            width: 1.5px
        id: 348d4e06-f4c8-4a0f-bbe5-94c79fea7ea7
        meshmodel-metadata:
          capabilities: |-
            {
              "fieldRefs": [
                {
                  "fieldPath": "spec.template.spec.containers",
                  "jsonSchemaPath": "properties.spec.allOf[0].properties.template.allOf[0].properties.spec.allOf[0].properties.containers.items.allOf[0]",
                  "component": {
                    "kind": "Container",
                    "model": "meshery-core"
                  },
                  "renderChildren": true
                }
              ],
              "designer": {
                "edit": {
                  "shape": {
                    "convert-shape": false
                  }
                }
              }
            }
          defaultData: ""
          genealogy: parent
          isAnnotation: false
          isCustomResource: false
          isModelAnnotation: "FALSE"
          isNamespaced: true
          logoURL: Created by Meshery Authors
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          secondaryColor: '#7aa1f0'
          shape: round-rectangle
          shapePolygonPoints: ""
          status: enabled
          styleOverrides:
            background-opacity: 0.5
            border-width: 2
            z-index: 3
          styles: '{"border-width":2,"background-opacity":0.5}'
          subCategory: ""
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/deployment-color.svg
          svgComplete: ui/public/static/img/meshmodels/kubernetes/complete/deployment-complete.svg
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/deployment-white.svg
        position:
          posX: -52.5
          posY: -62
        whiteboardData:
          style: {}
  sample-app-frontend-xismv:
    name: sample-app-frontend
    type: Service
    apiVersion: v1
    namespace: default
    model: kubernetes
    labels:
      app: sample-app-frontend
      app.kubernetes.io/instance: sample-app
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: sample-app
      app.kubernetes.io/version: 0.1.0
      helm.sh/chart: sample-app-0.1.0
    settings:
      spec:
        ports:
        - name: http
          port: 3000
          protocol: TCP
          target Port: http
        selector:
          app: sample-app-frontend
          app.kubernetes.io/instance: sample-app
          app.kubernetes.io/name: sample-app
        type: ClusterIP
    traits:
      meshmap:
        edges:
        - data:
            id: 0274aef1-7b3d-49a1-91fd-9c8978e74a25
            metadata:
              port: 3000
              protocol: TCP
            source: 141a267b-480a-451e-b7a6-4af5692dbca8
            subType: Network
            target: 348d4e06-f4c8-4a0f-bbe5-94c79fea7ea7
          style:
            control-point-distances: null
            control-point-weights: "0.5"
            curve-style: bezier
            haystack-radius: "0"
            line-color: rgb(153,153,153)
            line-style: dotted
            opacity: "1"
            segment-distances: 20px
            segment-weights: "0.5"
            target-arrow-shape: vee
            taxi-direction: auto
            taxi-turn: 50%
            taxi-turn-min-distance: 10px
            width: 1.5px
        id: 141a267b-480a-451e-b7a6-4af5692dbca8
        meshmodel-metadata:
          capabilities: ""
          defaultData: ""
          genealogy: ""
          isAnnotation: false
          isCustomResource: false
          isModelAnnotation: "FALSE"
          isNamespaced: true
          logoURL: https://github.com/cncf/artwork/blob/master/projects/kubernetes/icon/white/kubernetes-icon-white.svg
          model: kubernetes
          modelDisplayName: Kubernetes
          primaryColor: '#326CE5'
          secondaryColor: '#7aa1f0'
          shape: round-triangle
          shapePolygonPoints: ""
          status: enabled
          styleOverrides:
            background-position-y: 4.5
            height: 20
            padding: 12
            width: 20
            x: 10px
            "y": 12px
            z-index: 3
          styles: '{"height":20,"width":20,"padding":12,"background-position-y":4.5,"x":"10px","y":"12px"}'
          subCategory: ""
          svgColor: ui/public/static/img/meshmodels/kubernetes/color/service-color.svg
          svgComplete: ""
          svgWhite: ui/public/static/img/meshmodels/kubernetes/white/service-white.svg
        position:
          posX: 47.5
          posY: 20
        whiteboardData:
          style: {}
