name: Build and Deploy Site

on:
  pull_request:
    branches: [master]
    types: [opened, synchronize, reopened]
  workflow_dispatch:
permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4.2.2
        with:
          sparse-checkout: |
            install
            site
      - name: Install and Build 🔧 
        working-directory: site
        run: |
          make setup
          make build
      - name: Deploy to Netlify
        id: netlify
        uses: nwtgck/actions-netlify@v3.0.0
        with:
          publish-dir: 'public'
          production-deploy: false
          github-token: ${{ secrets.GH_ACCESS_TOKEN }}
          enable-commit-comment: false
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

      - name: Comment Deploy URL
        uses: ./.github/actions/comment-preview-on-pr
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          deploy_url: "${{ steps.netlify.outputs.deploy-url }}"
