name: Discussion data files update

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *' #runs every day at midnight

permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-24.04
    if: github.repository == 'meshery/meshery.io'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
      - name: Fetch data for meshery tag
        run: |
          curl -L http://discuss.meshery.io/tag/meshery.json -o _data/discuss/meshery.json
          sed -i 's|https://discuss.layer5.io|http://discuss.meshery.io|g' _data/discuss/meshery.json
          sed -i 's|discuss.layer5.io|discuss.meshery.io|g' _data/discuss/meshery.json

      - name: Pull changes from remote
        run: git pull origin master

      - name: Commit results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: l5io
          commit_user_email: ci@meshery.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: "--signoff"
          commit_message: "Updated meshery.json with new discussion posts"
          branch: master
