name: Discussion data files update

on:
  schedule:
    - cron: '0 0 * * *' #runs every day at midnight

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Fetch data for meshery tag
        run: curl https://discuss.layer5.io/tag/meshery.json -o _data/discuss/meshery.json
      - name: Commit results
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: l5io
          commit_user_email: ci@layer5.io
          commit_author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          commit_options: "--signoff"
          commit_message: "Updated meshery.json with new discussion posts"
          branch: master
